### ISSUE TITLE
Cannot run with Docker

### ISSUE THREAD

**Issue by MassiAtHG** [swoft-cloud/swoft#837]
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| Swoft version       | latest from git clone
| Swoole version      | the one installed in docker image swoft/swoft
| PHP version         | the one installed in docker image swoft/swoft
| Runtime environment | Docker

**Details**

> Describe what you are trying to achieve and what goes wrong.

After GIT cloning of the project I ran 'composer install'. All dependencies are installed properly.
I then run 'docker-compose up'; images are properly dowloaded and containers start running.
SWOFT container bails out a first time on following error: 

```
Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: [Semantical Error] Couldn't find constant Swoft\Server\SwooleEvent::SHUTDOWN, class App\Listener\DeregisterServiceListener. in /var/www/swoft/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
```
This first problem is easily solvable by finding instances of '**Swoft\Server\SwooleEvent**' replacing them with '**Swoft\Server\Swoole\SwooleEvent**'. 

When I start the container again, the following error occurs:
```
Fatal error: Interface 'Swoft\Process\Contract\ProcessInterface' not found in /var/www/swoft/app/Process/Worker2Process.php on line 23
```

The component '**swoft-process**' seems not to be installed, and trying to installing it manually with composer does not resolve correctly.

**Comment by inhere** [comment]
oo, sorry. We are ready to release the new version.
so, master contains some new feature codes.

you can:

```bash
git checkout v2.0.3
docker-composer up
```

**Comment by MassiAtHG** [comment]
With v2.0.3 all seems fine. I needed though to amend docker-compose.yml as the container command references '/var/www/swoft/bin/swoft' while docker-compose.yml volume is './:/var/www' (it should be './:/var/www/swoft')

**Comment by inhere** [comment]
@MassiAtHG  yes, we have fixed. will release on today.

**Comment by MassiAtHG** [comment]
Since this issue has been tagged a question, I would like to ask a couple.

Apart from the introduction of a very comprehensive events system, what are the biggest advantages of version 2 in comparison to version 1 of SWOFT?

What are good use cases for the 'breaker' module?

Thanks in advance for any reply.

**Comment by inhere** [comment]
@MassiAtHG the latest 2.0.4 version has been released. you can pull latest docker image.

diff with swoft 1:

- swoft 1 is our attempt, before there was no php framework like we did.
- In 1.0, because there are a lot of new things to think about, there are some places that may not be considered comprehensively, which makes it difficult to maintain the later stage of Swoft 1.
- In swoft 2 we absorbed 1.0 experience and rethought and planned a new 2.0 version on the basis of the previous
- The core of swoft 2.0 is completely rewritten, simplifying some unnecessary logic and clearer running process
- swoft 2.0 works with swoole 4.4+, discards non-co-scheduling usage, and runs applications using a full coroutine environment
- Swoft 2.0 db, redis has written complete unit tests to ensure the reliability of the components. Testing of other components is gradually being added

**Comment by MassiAtHG** [comment]
Thanks for your professionalism and the great work you are doing.
